version: '3.9'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: repolens-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - /tmp:/tmp
    networks:
      - repolens-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: repolens-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - repolens-network

networks:
  repolens-network:
    driver: bridge